apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: user-api-vs
spec:
  hosts:
    - "*"
  gateways:
    - k8s-demo-gateway
  http:
    - match:
        - uri:
            prefix: "/user-api"
      route:
        - destination:
            port:
              number: 8080
            host: user-api