apiVersion: v1
kind: Service
metadata:
  name: order-api
  labels:
    app: order-api
spec:
  selector:
    app: order-api
  ports:
    - port: 8080
      name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-v1
  labels:
    app: order-api
spec:
  selector:
    matchLabels:
      app: order-api
  replicas: 1
  template:
    metadata:
      labels:
        app: order-api
        version: v1
    spec:
      containers:
        - name: order-api
          image: run3wide/order-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: BPL_JVM_HEAD_ROOM
              value: "2"
            - name: BPL_JVM_LOADED_CLASS_COUNT
              value: "35"
            - name: BPL_JVM_THREAD_COUNT
              value: "10"
            - name: JAVA_OPTS
              value: >-
                -XX:ReservedCodeCacheSize=40M
                -XX:MaxMetaspaceSize=60M
                -Xlog:gc
                -Xms34m
                -Xmx40m
                -Xss256k
                -XX:MaxRAM=150M
