apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: k8s-demo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - "*"
